### ISSUE TITLE
`require': cannot load such file -- json (LoadError) - on Fedora

### ISSUE THREAD

**Issue by anshprat** [Shopify/dashing#232]
hi,

Its the same issue as https://github.com/Shopify/dashing/issues/89

filing a fresh one as thats closed.

Am on fedora 19.

dashing start fails.
$ dashing start
/usr/local/share/gems/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require': cannot load such file -- json (LoadError)

$ bundle exec thin start

> > Using rack adapter
> > /usr/local/share/gems/gems/backports-3.3.3/lib/backports/tools.rb:328:in `require': cannot load such file -- json (LoadError)

However thin start works.

$ thin start

> > Using rack adapter
> > Thin web server (v1.5.1 codename Straight Razor)
> > Maximum connections set to 1024
> > Listening on 0.0.0.0:3000, CTRL+C to stop

**Comment by akostadinov** [comment]
strangely on fedora 22 with rails 5, `bin/rails server` resulted in this. btw I have lots of gems installed. After adding `gem "json"` to Gemfile and `bundle install`, it started to work (as somebody mentioned in #89).
