### ISSUE TITLE
Problem with a job (scheduler caught exception)

### ISSUE THREAD

**Issue by LKLG** [Shopify/dashing#262]
I have a job to get data from a mysql-Database in the Rickshawgraph widget (https://gist.github.com/jwalton/6614023).
However, the job does not run.
Log:

```
================================================================================
scheduler caught exception:
tried to create Proc object without a block
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1526:in `define_method'
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1526:in `generate_method'
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1535:in `compile!'
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1515:in `route'
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1345:in `get'
/var/lib/gems/1.9.1/gems/sinatra-1.4.3/lib/sinatra/base.rb:1917:in `block (2 levels) in delegate'
/opt/dashing/jobs/otrs.rb:113:in `block (2 levels) in <top (required)>'
/opt/dashing/jobs/otrs.rb:112:in `each'
/opt/dashing/jobs/otrs.rb:112:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================

```

So i've looked at the script, but i doesn't find the problem.
"(0..7).each do |i|" is line 112

``` ruby
series = [
  {
    name:"Erstellte Tickets",
    data: []
  },
  {
    name:"Geschlossene Tickets",
    data: []
  }
]
z = 0

(0..7).each do |i|
  z = i - 1
  series[0][:data][z] = {x:prevdays(i,0,1), y:get(1)[0][i]}
  series[1][:data][z] = {x:prevdays(i,0,1), y:get(1)[0][i]}
end
```

So i tested the code with irb and there is no error or problem and everything is as it should.
So my question. Where is the Problem?

And sorry for my english..

**Comment by roastercode** [comment]
Got the same trouble too:

```
thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3333, CTRL+C to stop
== DEBUG: Nagios Stats
== DEBUG: API Services
== DEBUG: API Hostgroups
== DEBUG: API Hosts
== DEBUG: API Servicegroups
== DEBUG: API Servicegroups Int:0.498149278
3
{:servicegroupName=>"Smarteam Vault Storage Report Test", :servicegroupCount=>0, :servicegroupMembers=>[], :servicegroupConsolidatedStatus=>0}
{:hostName=>"CDSMART1SM.na.corp.cdaero.com", :hostStatus=>0, :hostAckOrSched=>0, :hostConsolidatedStatus=>0, :hostPublish=>0}
System - Disk Usage S:
================================================================================
scheduler caught exception:
undefined method `key?' for "System - Disk Usage S:":String
/usr/local/rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/model.rb:754:in `scoped_query'
/usr/local/rvm/gems/ruby-2.3.3/gems/dm-core-1.2.1/lib/dm-core/model.rb:342:in `all'
/home/aurelien/git/area51/smashing-zodiac/jobs/dumpAPI_Servicesgroups.rb:23:in `block (3 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'
/home/aurelien/git/area51/smashing-zodiac/jobs/dumpAPI_Servicesgroups.rb:17:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:187:in `block in each'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `upto'
/usr/local/rvm/gems/ruby-2.3.3/gems/nokogiri-1.6.8.1/lib/nokogiri/xml/node_set.rb:186:in `each'
/home/aurelien/git/area51/smashing-zodiac/jobs/dumpAPI_Servicesgroups.rb:12:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.3/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/rvm/gems/ruby-2.3.3/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/rvm/gems/ruby-2.3.3/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
================================================================================
== DEBUG: Nagios Stats Done: 0.840704166

```
