### ISSUE TITLE
Cannot deploy to Heroku

### ISSUE THREAD

**Issue by andrewlynch** [Shopify/dashing#482]
Runs perfectly on localhost.

Heroku error logs
```
2014-11-26T21:12:22.141799+00:00 heroku[web.1]: State changed from crashed to starting
2014-11-26T21:12:32.932667+00:00 heroku[web.1]: Starting process with command `bundle exec thin start -R config.ru -e production -p 23294`
2014-11-26T21:12:40.618062+00:00 app[web.1]: /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1/io/open.rb:2:in `close': Bad file descriptor - /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1/io/open.rb (Errno::EBADF)
2014-11-26T21:12:40.618144+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1/io/open.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618185+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618165+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618206+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:22:in `block in require_relative_dir'
2014-11-26T21:12:40.618123+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1/io/open.rb:2:in `open'
2014-11-26T21:12:40.618261+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1/io.rb:3:in `<top (required)>'
2014-11-26T21:12:40.618392+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618224+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:21:in `each'
2014-11-26T21:12:40.618243+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:21:in `require_relative_dir'
2014-11-26T21:12:40.618299+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618318+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:22:in `block in require_relative_dir'
2014-11-26T21:12:40.618430+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.2.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618410+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618336+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:21:in `each'
2014-11-26T21:12:40.618280+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618355+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:21:in `require_relative_dir'
2014-11-26T21:12:40.618373+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.1.rb:3:in `<top (required)>'
2014-11-26T21:12:40.618467+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618448+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618485+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.3.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618504+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618541+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/1.9.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618522+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618559+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618634+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618653+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/2.0.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618672+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618578+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618596+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/2.0.0.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618616+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618690+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618709+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/2.1.0.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618803+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618763+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/2.1.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618784+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618820+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports.rb:3:in `<top (required)>'
2014-11-26T21:12:40.618745+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
2014-11-26T21:12:40.618727+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require'
2014-11-26T21:12:40.618857+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/capture.rb:3:in `<top (required)>'
2014-11-26T21:12:40.618876+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/content_for.rb:2:in `require'
2014-11-26T21:12:40.618839+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/capture.rb:3:in `require'
2014-11-26T21:12:40.618894+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/sinatra-contrib-1.4.2/lib/sinatra/content_for.rb:2:in `<top (required)>'
2014-11-26T21:12:40.618951+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
2014-11-26T21:12:40.618913+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:3:in `require'
2014-11-26T21:12:40.618969+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
2014-11-26T21:12:40.618990+00:00 app[web.1]: 	from config.ru:1:in `require'
2014-11-26T21:12:40.618932+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/dashing-1.3.4/lib/dashing/app.rb:3:in `<top (required)>'
2014-11-26T21:12:40.619046+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
2014-11-26T21:12:40.619008+00:00 app[web.1]: 	from config.ru:1:in `block in <main>'
2014-11-26T21:12:40.619028+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
2014-11-26T21:12:40.619065+00:00 app[web.1]: 	from config.ru:1:in `new'
2014-11-26T21:12:40.619102+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `eval'
2014-11-26T21:12:40.619084+00:00 app[web.1]: 	from config.ru:1:in `<main>'
2014-11-26T21:12:40.619120+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/rack/adapter/loader.rb:33:in `load'
2014-11-26T21:12:40.619211+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/thin/runner.rb:155:in `run!'
2014-11-26T21:12:40.619230+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/bin/thin:6:in `<top (required)>'
2014-11-26T21:12:40.619157+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:72:in `start'
2014-11-26T21:12:40.619193+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/thin/runner.rb:199:in `run_command'
2014-11-26T21:12:40.619249+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in `load'
2014-11-26T21:12:40.619268+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/bin/thin:23:in `<main>'
2014-11-26T21:12:40.619139+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.0.0/gems/thin-1.6.2/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
2014-11-26T21:12:41.561471+00:00 heroku[web.1]: State changed from starting to crashed
```

**Comment by tylermauthe** [comment]
Seems to have been answered here too:
http://stackoverflow.com/questions/27167440/dashing-does-not-run-on-heroku

**Comment by eddiejaoude** [comment]
@tylermauthe thanks I will give it a try

> I fixed this by running:
> bundle update back ports
> and making sure my Gemfile.lock was updated and committed.

**Comment by pushmatrix** [comment]
Closing for now. If @tylermauthe's suggestion doesn't work, just re-open.
