### ISSUE TITLE
Unexpected error encountered with example

### ISSUE THREAD

**Issue by Jaff** [Shopify/dashing#528]
Running on RHEL 6.4, fresh install of ruby 1.8.7, rubygems-2.4.6, dashing-1.3.4, I did the incantation "dashing new sweet_dashboard_project" and then cd into sweet_dashboard_project and did "bundle" with the following results:
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies...
Installing addressable 2.3.7
Using backports 3.6.4
Installing buftok 0.2.0
Using coffee-script-source 1.9.1
Using execjs 2.0.2
Using coffee-script 2.2.0
Using daemons 1.1.9
Using rack 1.5.2
Using thread_safe 0.3.4
Using tzinfo 1.2.2
Using rufus-scheduler 2.0.24
Using sass 3.2.19
Using rack-protection 1.5.3
Using tilt 1.4.1
Using sinatra 1.4.5
Using multi_json 1.10.1
Using rack-test 0.6.3
Using sinatra-contrib 1.4.2
Using hike 1.2.3
Using sprockets 2.10.2
Using eventmachine 1.0.7
Using thin 1.6.3
Using thor 0.18.1
Using dashing 1.3.4
Installing equalizer 0.0.9
Installing multipart-post 2.0.0
Installing faraday 0.9.1
Installing http_parser.rb 0.6.0
Installing http 0.6.3
Using json 1.8.2
Installing memoizable 0.4.2
Installing naught 1.0.0
Installing simple_oauth 0.3.1
Installing twitter 5.14.0
Using bundler 1.8.3
Bundle complete! 2 Gemfile dependencies, 35 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
Then I did "dashing start" and saw this result:
/usr/lib64/ruby/gems/1.8/gems/dashing-1.3.4/lib/dashing.rb:3:in `require': /usr/lib64/ruby/gems/1.8/gems/dashing-1.3.4/lib/dashing/app.rb:31: syntax error, unexpected ':', expecting $end (SyntaxError)
set server: 'thin', connections: [], history_file: 'history.yml'
           ^
	from /usr/lib64/ruby/gems/1.8/gems/dashing-1.3.4/lib/dashing.rb:3
	from config.ru:1:in `require'
	from config.ru:1
	from /usr/lib64/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/lib64/ruby/gems/1.8/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1

**Comment by wlads** [comment]
Hi there, let me shout out: ruby 1.8.7 has been EOL on 30 Jun 2013 [we-retire-1-8-7](https://www.ruby-lang.org/en/news/2013/06/30/we-retire-1-8-7/) after 5 good years of run [ruby-1-8-7-has-been-released](https://www.ruby-lang.org/en/news/2008/05/31/ruby-1-8-7-has-been-released/).

IMHO you should try with newer versions (if possible ~> 2.2.0) and shout back any problems :smile: 

Regards
