### ISSUE TITLE
Install on CentOS Linux release 7.0.1406 (Core) json error

### ISSUE THREAD

**Issue by nickjohnsonm** [Shopify/dashing#546]
Steps done:

yum install -y ruby ruby-dev gem
yum install -y rubygem-bundler
yum install -y gcc-c++
yum install -y make
curl -sL https://rpm.nodesource.com/setup | bash -
yum install -y nodejs
yum install ruby-devel
gem install dashing
dashing new proj
cd proj
rm jobs/twitter.rb
"update Gemfile to remove twitter"
dashing start -p 80

and get this:

/usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `require': cannot load such file -- json (LoadError)
	from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `<top (required)>'
	from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing.rb:2:in `require'
	from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing.rb:2:in `<top (required)>'
	from config.ru:1:in `require'
	from config.ru:1:in `block in <main>'
	from /usr/local/share/gems/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/share/gems/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from config.ru:1:in `new'
	from config.ru:1:in `<main>'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
	from /usr/local/share/gems/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
	from /usr/local/share/gems/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
	from /usr/local/bin/thin:23:in `load'
	from /usr/local/bin/thin:23:in `<main>'

**Comment by tylermauthe** [comment]
Have you invoked Bundler to install the bundle from Gemfile?

If not, make sure you have Bundler installed: `gem install bundler`
Then cd to your dashing directory and run: `bundle install`

**Comment by nickjohnsonm** [comment]
Did with both 
    yum install -y rubygem-bundler
and
    gem install bundler

I suspect may be from some items using /usr/share/gems and /usr/local/share.

I'm trying to follow the instructions without doing any symlinks or anything.

**Comment by tylermauthe** [comment]
You need to actually run bundler to install the bundle though...

Did you do this:
> Then cd to your dashing directory and run: bundle install

**Comment by nickjohnsonm** [comment]
Yes, both times.

For Ubuntu slide 4 of this http://www.slideshare.net/larrycai/learn-dashing-widget-in-90-minutes works fine, no issues.  

Just having these issues with installing on CentOS.

Thanks

**Comment by tylermauthe** [comment]
Can you please paste the output from this:
`cd /path/to/dashingProject && bundle --verbose`

**Comment by nickjohnsonm** [comment]
`cd /proj && bundle --verbose`

Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
Using backports 3.6.4
0:  backports (3.6.4) from /usr/local/share/gems/specifications/backports-3.6.4.gemspec
Using coffee-script-source 1.9.1
0:  coffee-script-source (1.9.1) from /usr/local/share/gems/specifications/coffee-script-source-1.9.1.gemspec
Using execjs 2.0.2
0:  execjs (2.0.2) from /usr/local/share/gems/specifications/execjs-2.0.2.gemspec
Using coffee-script 2.2.0
0:  coffee-script (2.2.0) from /usr/local/share/gems/specifications/coffee-script-2.2.0.gemspec
Using daemons 1.2.2
0:  daemons (1.2.2) from /usr/local/share/gems/specifications/daemons-1.2.2.gemspec
Using rack 1.5.2
0:  rack (1.5.2) from /usr/local/share/gems/specifications/rack-1.5.2.gemspec
Using thread_safe 0.3.5
0:  thread_safe (0.3.5) from /usr/local/share/gems/specifications/thread_safe-0.3.5.gemspec
Using tzinfo 1.2.2
0:  tzinfo (1.2.2) from /usr/local/share/gems/specifications/tzinfo-1.2.2.gemspec
Using rufus-scheduler 2.0.24
0:  rufus-scheduler (2.0.24) from /usr/local/share/gems/specifications/rufus-scheduler-2.0.24.gemspec
Using sass 3.2.19
0:  sass (3.2.19) from /usr/local/share/gems/specifications/sass-3.2.19.gemspec
Using rack-protection 1.5.3
0:  rack-protection (1.5.3) from /usr/local/share/gems/specifications/rack-protection-1.5.3.gemspec
Using tilt 1.4.1
0:  tilt (1.4.1) from /usr/local/share/gems/specifications/tilt-1.4.1.gemspec
Using sinatra 1.4.6
0:  sinatra (1.4.6) from /usr/local/share/gems/specifications/sinatra-1.4.6.gemspec
Using multi_json 1.11.0
0:  multi_json (1.11.0) from /usr/local/share/gems/specifications/multi_json-1.11.0.gemspec
Using rack-test 0.6.3
0:  rack-test (0.6.3) from /usr/local/share/gems/specifications/rack-test-0.6.3.gemspec
Using sinatra-contrib 1.4.2
0:  sinatra-contrib (1.4.2) from /usr/local/share/gems/specifications/sinatra-contrib-1.4.2.gemspec
Using hike 1.2.3
0:  hike (1.2.3) from /usr/local/share/gems/specifications/hike-1.2.3.gemspec
Using sprockets 2.10.2
0:  sprockets (2.10.2) from /usr/local/share/gems/specifications/sprockets-2.10.2.gemspec
Using eventmachine 1.0.7
0:  eventmachine (1.0.7) from /usr/local/share/gems/specifications/eventmachine-1.0.7.gemspec
Using thin 1.6.3
0:  thin (1.6.3) from /usr/local/share/gems/specifications/thin-1.6.3.gemspec
Using thor 0.18.1
0:  thor (0.18.1) from /usr/local/share/gems/specifications/thor-0.18.1.gemspec
Using dashing 1.3.4
0:  dashing (1.3.4) from /usr/local/share/gems/specifications/dashing-1.3.4.gemspec
Using bundler 1.9.1
0:  bundler (1.9.1) from /usr/local/share/gems/specifications/bundler-1.9.1.gemspec
Bundle complete! 1 Gemfile dependency, 23 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.

**Comment by tylermauthe** [comment]
Great, it looks like your bundle is installed... You should be able to skirt any issues with the environment by running dashing from the bundle:
`bundle exec dashing start`

Let me know if that works...

**Comment by nickjohnsonm** [comment]
`bundle exec dashing start`

`/usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `require': cannot load such file -- json (LoadError)
	from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/downloader.rb:3:in `<top (required)>'
	from /usr/local/share/gems/gems/dashing-1.3.4/bin/dashing:7:in `require'
	from /usr/local/share/gems/gems/dashing-1.3.4/bin/dashing:7:in `<top (required)>'
	from /usr/local/bin/dashing:23:in `load'
	from /usr/local/bin/dashing:23:in `<main>'
`

The exception is now "shorter"

**Comment by ilkerde** [comment]
@nickjohnsonm Found a way to get it running? I am facing same issues.

**Comment by if13b023** [comment]
Got the same problem...any suggestions?

**Comment by Logrythmik** [comment]
SAME issue on every OS...
