### ISSUE TITLE
Solved:  Error starting dashing on SLES 11 SP3 with Ruby 1.9.3

### ISSUE THREAD

**Issue by clohtd** [Shopify/dashing#557]
```
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require': cannot load such file -- twitter (LoadError)
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /data01/opt/dashing_ctms/jobs/twitter.rb:1:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/backports-3.6.4/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `load'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/thin:23:in `<main>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by clohtd** [comment]
Solved by adding these two lines to the bottom of the Gemfile

```
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
```

Entire Gemfile now looks like this:

```
source 'https://rubygems.org'

gem 'dashing'

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
gem 'execjs'
gem 'therubyracer', :platforms => :ruby
```
