### ISSUE TITLE
Current recommended version of ruby?

### ISSUE THREAD

**Issue by OliPassey** [Shopify/dashing#607]
Hi, Im a new user of Dashing and have so far managed to get only the initial sample dash up and running. As i try to install various additional widgets i hit problems and find my install in a broken state that needs to be trashed and i have to begin again.

It seems im running into version issues, some widgets such as Mailchimp ones require gibbon, which says it need Ruby 2, but im new to ruby also and again it leads me to a broken install. original sample works, but when i stop to install mailchimp, and then bundle, then dashing start it fails miserably

I can host this on any platform it wants - im just not sure where it would be happiest.
And if i should stick with ruby 1.9.3 as the wiki says, or go for ruby 2.2.2 in the hope i can use all of the latest widgets people are creating.

Any advice would be much appreciated.
Cheers

**Comment by OliPassey** [comment]
c:\Ruby22-x64\foe>dashing start
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/backends/base.rb:103: warning: epoll is not supported on this platform
C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require': cannot load such file -- gibbon (LoadError)
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
        from c:/Ruby22-x64/foe/jobs/mailchimp.rb:1:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/backports-3.6.6/lib/backports/std_lib.rb:9:in `require_with_backports'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/app.rb:157:in `block in require_glob'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `each'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/app.rb:156:in `require_glob'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `<top (required)>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/controllers/controller.rb:72:in `start'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
        from C:/Ruby22-x64/lib/ruby/gems/2.2.0/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
        from C:/Ruby22-x64/bin/thin:23:in `load'
        from C:/Ruby22-x64/bin/thin:23:in `<main>'

This is the current error im getting on load after installing gibbon. 
Very confused :(

**Comment by snario** [comment]
+1
