### ISSUE TITLE
ruby_http_parser (LoadError)

### ISSUE THREAD

**Issue by chasbutt** [Shopify/dashing#652]
I was able to get dashing running under CentOS, but I need to use RHEL 7.1 for production. I have gotten stumped by the error below. When running into similar "LoadError" issues, adding the gem to the Gemfile has taken care of it, but not in this case. The error is shown, followed by the Gemfile and the list of installed Gems. FYI --- this is the first ruby project I have ever worked on. I am also working from behind a firewall that prevents me from just running 'gem install dashing.'  The CentOS install was much easier because I had internet access, figured out the process and all the gems needed. Then I downloaded them and have been doing local installs on RHEL.

ERROR
$ dashing start
/usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require': cannot load such file -- ruby_http_parser (LoadError)
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http_parser.rb:2:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/http_parser.rb-0.6.0/lib/http/parser.rb:1:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:1:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:5:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/twitter-5.15.0/lib/twitter.rb:26:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /home/cbutter/mydashb2/jobs/twitter.rb:1:in `<top (required)>'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require'
        from /usr/local/share/gems/gems/backports-3.6.7/lib/backports/std_lib.rb:9:in `require_with_backports'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/app.rb:168:in `block in require_glob'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `each'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/app.rb:167:in `require_glob'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing/app.rb:178:in `<top (required)>'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing.rb:3:in `require'
        from /usr/local/share/gems/gems/dashing-1.3.4/lib/dashing.rb:3:in `<top (required)>'
        from config.ru:1:in `require'
        from config.ru:1:in `block in <main>'
        from /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `instance_eval'
        from /usr/local/share/gems/gems/rack-1.5.5/lib/rack/builder.rb:55:in `initialize'
        from config.ru:1:in `new'
        from config.ru:1:in `<main>'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `eval'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/rack/adapter/loader.rb:33:in `load'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /usr/local/share/gems/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /usr/local/share/gems/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'
$ 

Gemfile

$ cat Gemfile
source 'https://rubygems.org'

gem 'dashing'
gem 'ruby_http_parser'
gem 'json'
gem 'therubyracer', :platforms => :ruby

## Remove this if you don't need a twitter widget.
gem 'twitter', '>= 5.9.0'
$ 

Gems

$ gem list

*** LOCAL GEMS ***

addressable (2.4.0)
backports (3.6.7)
bigdecimal (1.2.0)
buftok (0.2.0)
bundle (0.0.1)
bundler (1.11.1)
coffee-script (2.2.0)
coffee-script-source (1.10.0)
daemons (1.2.3)
dashing (1.3.4)
domain_name (0.5.25)
equalizer (0.0.10)
eventmachine (1.0.8)
execjs (2.0.2)
faraday (0.9.0)
hike (1.2.3)
http (0.9.8)
http-cookie (1.0.2)
http-form_data (1.0.1)
http_parser.rb (0.6.0)
io-console (0.4.2)
json (1.8.3, 1.7.7)
libv8 (3.16.14.13 x86_64-linux)
memoizable (0.4.2)
multi_json (1.11.2)
multipart-post (2.0.0)
naught (1.1.0)
psych (2.0.0)
rack (1.5.5)
rack-protection (1.5.3)
rack-test (0.6.3)
rdoc (4.0.0)
ref (2.0.0)
ruby_http_parser (0.0.1)
rufus-scheduler (2.0.24)
sass (3.2.19)
simple_oauth (0.3.1)
sinatra (1.4.6)
sinatra-contrib (1.4.6)
sprockets (2.10.2)
therubyracer (0.12.2)
thin (1.6.4)
thor (0.19.1)
thread_safe (0.3.5)
tilt (1.4.1)
twitter (5.15.0)
tzinfo (1.2.2)
unf (0.1.4)
unf_ext (0.0.7.1)
$

**Comment by chasbutt** [comment]
commented out everything in mydasb2/jobs/twitter.rb and I was able to get dashing to start. I had tried to not require twitter in the first place, but for some reason, that didn't work. In any case, it is running now without twitter.
