### ISSUE TITLE
Dashing start command fails in Tmux session

### ISSUE THREAD

**Issue by nakulpathak3** [Shopify/dashing#691]
When I run the dashing start command in a tmux session, it errors out. But the same command after exiting Tmux, works perfectly. This is within a vagrant session running Oracle Linux 6.5. I am also using `rvm`. From the logs, it seems that is relevant as well.

To reproduce, open terminal, go to a dashing app, run the following - 

```
➜  dashing start
LOGGING_LEVEL = 1
Thin web server (v1.6.4 codename Gob Bluth)
Maximum connections set to 1024
Listening on 0.0.0.0:3030, CTRL+C to stop
^C/home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/dashing-1.3.4/lib/dashing/cli.rb:89:in `system': Interrupt
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/dashing-1.3.4/lib/dashing/cli.rb:89:in `run_command'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/dashing-1.3.4/lib/dashing/cli.rb:64:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/thor-0.18.1/lib/thor/command.rb:27:in `run'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/thor-0.18.1/lib/thor/invocation.rb:120:in `invoke_command'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/thor-0.18.1/lib/thor.rb:363:in `dispatch'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/thor-0.18.1/lib/thor/base.rb:439:in `start'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/gems/dashing-1.3.4/bin/dashing:9:in `<top (required)>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/bin/dashing:23:in `load'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/bin/dashing:23:in `<main>'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/bin/ruby_executable_hooks:15:in `eval'
        from /home/vagrant/.rvm/gems/ruby-2.3.0@gl/bin/ruby_executable_hooks:15:in `<main>'

➜  Stopping ...

➜  ps aux | grep ruby
vagrant  23031  0.0  0.0 103360   840 pts/1    S+   03:22   0:00 grep --color=auto --exclude-dir=.bzr --exclude-dir=CVS --exclude-dir=.git --exclude-dir=.hg --exclude-dir=.svn ruby
➜  tmux new
➜  dashing start
ERRORS (about 300 lines, thus not including entire log for now).
```

**Comment by howardsternisbatman** [comment]
you look to be trying to run to instances of dashing on the same port (3030)

try this for the 2nd command. 

dashing start -p 3031

**Comment by nakulpathak3** [comment]
My bad, This is after I stopped the first instance and started tmux. I'll update the description
