### ISSUE TITLE
Dashboard would not start - Raspberry Pi

### ISSUE THREAD

**Issue by latitjuig** [Shopify/dashing#698]
Hi, please help. The dashboard ran fine, then all of a sudden i got this message. Please help

pi@raspberrypi:/opt/dashboard/dashboards $ dashing start
/var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `read': No such file or directory @ rb_sysopen - config.ru (Errno::ENOENT)
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/rack/adapter/loader.rb:32:in `load'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:182:in `load_rackup_config'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/controllers/controller.rb:72:in `start'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:200:in `run_command'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/lib/thin/runner.rb:156:in `run!'
        from /var/lib/gems/2.1.0/gems/thin-1.6.4/bin/thin:6:in `<top (required)>'
        from /usr/local/bin/thin:23:in `load'
        from /usr/local/bin/thin:23:in `<main>'

**Comment by and7ey** [comment]
@latitjuig, something happened with your `config.ru` file. Probably, you've uploaded the dashing itself instead of dashing project (if you are talking about production).
