### ISSUE TITLE
Error installing: cannot load such file -- devkit.rb (LoadError)

### ISSUE THREAD

**Issue by fractalbeauty** [Shopify/dashing#733]
Stack:
```
C:\>gem install dashing
C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/defaults/operating_system.rb:3:in `load': cannot load such file -- devkit.rb (LoadError)
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/defaults/operating_system.rb:3:in `block in <top (required)>'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:329:in `block in run_pre_install_hooks'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:328:in `each'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:328:in `run_pre_install_hooks'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:283:in `install'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/resolver/specification.rb:97:in `install'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:166:in `block in install'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:156:in `each'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/request_set.rb:156:in `install'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:205:in `install_gem'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:255:in `block in install_gems'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `each'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:251:in `install_gems'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/commands/install_command.rb:158:in `execute'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/command.rb:310:in `invoke_with_build_args'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:169:in `process_args'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/command_manager.rb:139:in `run'
        from C:/Ruby23/lib/ruby/site_ruby/2.3.0/rubygems/gem_runner.rb:55:in `run'
        from C:/Ruby23/bin/gem:21:in `<main>'
```

I have the DevKit installed and was able to install gems requiring the DevKit previously, could anyone help me out?

**Comment by MartynKeigher** [comment]
Can you please put your `operating_system.rb` file here please?

TO add: I had sporadic issues with Dashing on windows using Ruby 2.3, I held it back to **2.2.6**.
