### ISSUE TITLE
Issue Installing on Raspberry Pi

### ISSUE THREAD

**Issue by Lynchmenow** [Shopify/dashing#749]
I have been trying to get Dashing going on a Raspberry Pi but can't get past this issue.  

    sudo gem install dashing
    Building native extensions.  This could take a while...
    ERROR:  Error installing dashing:
        ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/eventmachine-1.2.5/ext
    /usr/bin/ruby2.3 -r ./siteconf20170806-7796-1b94ap9.rb extconf.rb
    *** extconf.rb failed ***
    Could not create Makefile due to some reason, probably lack of necessary
    libraries and/or headers.  Check the mkmf.log file for more details.  You may
    need configuration options.

    Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
        --with-ssl-dir
        --without-ssl-dir
        --with-ssl-include
        --without-ssl-include=${ssl-dir}/include
        --with-ssl-lib
        --without-ssl-lib=${ssl-dir}/lib
        --with-openssl-config
        --without-openssl-config
        --with-pkg-config
        --without-pkg-config
    /usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. 
    (RuntimeError)
    You have to install development tools first.
        from /usr/lib/ruby/2.3.0/mkmf.rb:541:in `try_link0'
        from /usr/lib/ruby/2.3.0/mkmf.rb:556:in `try_link'
        from /usr/lib/ruby/2.3.0/mkmf.rb:657:in `try_ldflags'
        from /usr/lib/ruby/2.3.0/mkmf.rb:1813:in `pkg_config'
        from extconf.rb:65:in `pkg_config_wrapper'
        from extconf.rb:92:in `<main>'

    To see why this extension failed to compile, please check the mkmf.log which can be found here:

    /var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/eventmachine-1.2.5/mkmf.log

    extconf failed, exit code 1

    Gem files will remain installed in /var/lib/gems/2.3.0/gems/eventmachine-1.2.5 for inspection.
    Results logged to /var/lib/gems/2.3.0/extensions/arm-linux/2.3.0/eventmachine-
    1.2.5/gem_make.out`

Can someone please help?

**Comment by lepetitcreole** [comment]
Hi, I had the same issue. To solve it :
sudo apt-get install ruby-dev
